##### Copyright 2022 The Cirq Developers

In [1]:
# @title Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Hello Qubit

<table class="tfo-notebook-buttons" align="left">
  <td>
    <a target="_blank" href="https://quantumai.google/cirq/start/start"><img src="https://quantumai.google/site-assets/images/buttons/quantumai_logo_1x.png" />View on QuantumAI</a>
  </td>
  <td>
    <a target="_blank" href="https://colab.research.google.com/github/quantumlib/Cirq/blob/main/docs/start/start.ipynb"><img src="https://quantumai.google/site-assets/images/buttons/colab_logo_1x.png" />Run in Google Colab</a>
  </td>
  <td>
    <a target="_blank" href="https://github.com/quantumlib/Cirq/blob/main/docs/start/start.ipynb"><img src="https://quantumai.google/site-assets/images/buttons/github_logo_1x.png" />View source on GitHub</a>
  </td>
  <td>
    <a href="https://storage.googleapis.com/tensorflow_docs/Cirq/docs/start/start.ipynb"><img src="https://quantumai.google/site-assets/images/buttons/download_icon_1x.png" />Download notebook</a>
  </td>
</table>

In [1]:
try:
    import cirq
except ImportError:
    print("installing cirq...")
    !pip install --quiet cirq
    import cirq

    print("installed cirq.")

installing cirq...
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 102.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 670.8/670.8 kB 53.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.5/73.5 kB 8.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 430.5/430.5 kB 40.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 116.9 MB/s eta 0:00:00
installed cirq.


In [2]:
# Pick a qubit.
qubit = cirq.GridQubit(0, 0)

# Create a circuit that applies a square root of NOT gate, then measures the qubit.
circuit = cirq.Circuit(cirq.X(qubit) ** 0.5, cirq.measure(qubit, key='m'))
print("Circuit:")
print(circuit)

# Simulate the circuit several times.
simulator = cirq.Simulator()
result = simulator.run(circuit, repetitions=20)
print("Results:")
print(result)

Circuit:
(0, 0): ───X^0.5───M('m')───
Results:
m=11001000000011011001


# Congratulations
You've just run your first Cirq program.

To learn about running a circuit on a virtual machine that mimics existing quantum hardware, see [Quantum Virtual Machine](../simulate/quantum_virtual_machine.ipynb).

If you would like to learn more about quantum computing, check out our [education page](https://quantumai.google/resources). The Full API reference for Cirq can be found [here](/reference/python/cirq). If you are looking for vendor specific information that can be found on our vendor sub-pages:


  [Alpine Quantum Technologies](../hardware/aqt/getting_started.ipynb)
  
  [Pasqal](../hardware/pasqal/getting_started.ipynb)
  
  [IonQ](../hardware/ionq/getting_started.ipynb)
  
  [Azure](../hardware/azure-quantum/getting_started_honeywell.ipynb)

In [3]:
# CELL 1: INSTALL DEPENDENCIES
# Runtime: ~3-4 minutes on first run
# ============================================================

!pip install pennylane --quiet
!pip install pennylane-cirq --quiet
!pip install cirq --quiet

# RDKit for molecular fingerprint generation
!pip install rdkit --quiet

# ChEMBL web resource client for programmatic download
!pip install chembl-webresource-client --quiet

# Standard ML + visualization
!pip install scikit-learn matplotlib seaborn pandas numpy --quiet

print("✅ All packages installed successfully!")

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.3/57.3 kB 5.8 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.3/5.3 MB 129.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 935.6/935.6 kB 53.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.9/167.9 kB 18.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.5/2.5 MB 75.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.2/2.2 MB 100.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.9/8.9 MB 119.0 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 36.7/36.7 MB 24.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 55.2/55.2 kB 5.7 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.2/70.2 kB 8.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 73.1/73.1 kB 9.0 MB/s eta 0:00:00
✅ All packages installed successfully!


In [4]:
# ============================================================
# CELL 2: IMPORTS
# ============================================================

# --- Quantum ---
import pennylane as qml
from pennylane import numpy as np

# --- Classical ML ---
import numpy as classical_np
import pandas as pd
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split, StratifiedKFold
from sklearn.metrics import (
    f1_score, precision_score, recall_score,
    roc_auc_score, confusion_matrix,
    classification_report, roc_curve
)
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.pipeline import Pipeline

# --- Molecular Encoding ---
from rdkit import Chem
from rdkit.Chem import AllChem, Descriptors
from rdkit.Chem.rdMolDescriptors import GetMorganFingerprintAsBitVect

# --- Data Download ---
from chembl_webresource_client.new_client import new_client

# --- Visualization ---
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

# --- Misc ---
import time
import json

# ---- Reproducibility ----
SEED = 42
classical_np.random.seed(SEED)

print(f"✅ PennyLane version: {qml.__version__}")
print("✅ All imports successful!")

✅ PennyLane version: 0.44.1
✅ All imports successful!


In [14]:
# ============================================================
# CELL 4: DATA PREPROCESSING
# Steps:
#  1. Drop nulls
#  2. Convert all values to nM-equivalent
#  3. Label: Active (<= 1000 nM) = 1, Inactive (> 1000 nM) = 0
#  4. Remove duplicate SMILES
#  5. Validate SMILES with RDKit
# ============================================================

df = df_raw.copy()

# --- Step 1: Drop nulls ---
df.dropna(subset=['Smiles', 'Standard Value'], inplace=True)
df['Standard Value'] = pd.to_numeric(df['Standard Value'], errors='coerce')
df.dropna(subset=['Standard Value'], inplace=True)
print(f"After null removal: {len(df)} records")

# --- Step 2: Unit normalization to nM ---
def normalize_to_nM(row):
    val = row['Standard Value']
    unit = str(row['Standard Units'])
    if unit == 'uM':
        return val * 1000
    elif unit in ['ug/mL', 'ug.mL-1']:
        return val * 1000  # approximate
    else:  # nM already
        return val

df['value_nM'] = df.apply(normalize_to_nM, axis=1)

# --- Step 3: Binary labeling ---
# Research standard: IC50 <= 1000 nM = Active antibiotic candidate
ACTIVITY_THRESHOLD_NM = 1000
df['label'] = (df['value_nM'] <= ACTIVITY_THRESHOLD_NM).astype(int)

print(f"\n🎯 Label Distribution:")
print(df['label'].value_counts())
print(f"Active (1): {df['label'].sum()} | Inactive (0): {(df['label']==0).sum()}")

# --- Step 4: Remove duplicate SMILES, keep first ---
df.drop_duplicates(subset='Smiles', keep='first', inplace=True)
print(f"\nAfter deduplication: {len(df)} unique molecules")

# --- Step 5: Validate SMILES with RDKit ---
def is_valid_smiles(smi):
    try:
        mol = Chem.MolFromSmiles(smi)
        return mol is not None
    except:
        return False

df['valid'] = df['Smiles'].apply(is_valid_smiles)
df = df[df['valid'] == True].copy()
print(f"After SMILES validation: {len(df)} molecules")
print(f"\n✅ Final dataset shape: {df.shape}")

# Save clean dataset
df.to_csv('chembl357_clean.csv', index=False)
print("💾 Saved: chembl357_clean.csv")

After null removal: 14107 records

🎯 Label Distribution:
label
0    10078
1     4029
Name: count, dtype: int64
Active (1): 4029 | Inactive (0): 10078

After deduplication: 7471 unique molecules
After SMILES validation: 7471 molecules

✅ Final dataset shape: (7471, 51)
💾 Saved: chembl357_clean.csv


In [10]:
print("Inspecting the first few lines of the CSV file:")
file_path = "/content/DOWNLOAD-vvOabsWMRJtYBGsrPC8SVYCHHmdlMQIArGsaz3fU2jQ_eq_.csv"

try:
    with open(file_path, 'r', encoding='utf-8') as f:
        for i, line in enumerate(f):
            print(line.strip())
            if i >= 10: # Print first 10 lines
                break
except Exception as e:
    print(f"Could not read file content: {e}")

Inspecting the first few lines of the CSV file:
"Molecule ChEMBL ID";"Molecule Name";"Molecule Max Phase";"Molecular Weight";"#RO5 Violations";"AlogP";"Compound Key";"Smiles";"Standard Type";"Standard Relation";"Standard Value";"Standard Units";"pChEMBL Value";"Data Validity Comment";"Comment";"Uo Units";"Ligand Efficiency BEI";"Ligand Efficiency LE";"Ligand Efficiency LLE";"Ligand Efficiency SEI";"Potential Duplicate";"Assay ChEMBL ID";"Assay Description";"Assay Type";"BAO Format ID";"BAO Label";"Assay Organism";"Assay Tissue ChEMBL ID";"Assay Tissue Name";"Assay Cell Type";"Assay Subcellular Fraction";"Assay Parameters";"Assay Variant Accession";"Assay Variant Mutation";"Target ChEMBL ID";"Target Name";"Target Organism";"Target Type";"Document ChEMBL ID";"Source ID";"Source Description";"Document Journal";"Document Year";"Cell ChEMBL ID";"Properties";"Action Type";"Standard Text Value";"Value"
"CHEMBL439555";"";"None";"2576.15";"None";"None";"53";"Cc1cc(C)cc(CC(=O)N[C@@H](CC(N)=O)C(=

In [13]:
import pandas as pd

# The file path was provided in the context.
file_path = "/content/DOWNLOAD-vvOabsWMRJtYBGsrPC8SVYCHHmdlMQIArGsaz3fU2jQ_eq_.csv"

print("📥 Loading dataset from local file...")

try:
    df_raw = pd.read_csv(file_path, sep=';') # Specify semicolon as delimiter
    print(f"\n✅ Loaded {len(df_raw)} bioactivity records")
    print(f"📊 Columns: {list(df_raw.columns)}")
    display(df_raw.head())
except FileNotFoundError:
    print(f"Error: The file '{file_path}' was not found. Please ensure the file is uploaded or the path is correct.")
except pd.errors.ParserError as e:
    print(f"Error parsing CSV: {e}\nAttempting to read with a different engine (python) and error_bad_lines=False...")
    try:
        df_raw = pd.read_csv(file_path, engine='python', on_bad_lines='skip', sep=';')
        print(f"Successfully loaded with 'python' engine and skipping bad lines. Records loaded: {len(df_raw)}")
        print(f"📊 Columns: {list(df_raw.columns)}")
        display(df_raw.head())
    except Exception as inner_e:
        print(f"Further error during re-attempt: {inner_e}")
except Exception as e:
    print(f"An unexpected error occurred while loading the CSV: {e}")

📥 Loading dataset from local file...

✅ Loaded 15030 bioactivity records
📊 Columns: ['Molecule ChEMBL ID', 'Molecule Name', 'Molecule Max Phase', 'Molecular Weight', '#RO5 Violations', 'AlogP', 'Compound Key', 'Smiles', 'Standard Type', 'Standard Relation', 'Standard Value', 'Standard Units', 'pChEMBL Value', 'Data Validity Comment', 'Comment', 'Uo Units', 'Ligand Efficiency BEI', 'Ligand Efficiency LE', 'Ligand Efficiency LLE', 'Ligand Efficiency SEI', 'Potential Duplicate', 'Assay ChEMBL ID', 'Assay Description', 'Assay Type', 'BAO Format ID', 'BAO Label', 'Assay Organism', 'Assay Tissue ChEMBL ID', 'Assay Tissue Name', 'Assay Cell Type', 'Assay Subcellular Fraction', 'Assay Parameters', 'Assay Variant Accession', 'Assay Variant Mutation', 'Target ChEMBL ID', 'Target Name', 'Target Organism', 'Target Type', 'Document ChEMBL ID', 'Source ID', 'Source Description', 'Document Journal', 'Document Year', 'Cell ChEMBL ID', 'Properties', 'Action Type', 'Standard Text Value', 'Value']


,Molecule ChEMBL ID,Molecule Name,Molecule Max Phase,Molecular Weight,#RO5 Violations,AlogP,Compound Key,Smiles,Standard Type,Standard Relation,...,Document ChEMBL ID,Source ID,Source Description,Document Journal,Document Year,Cell ChEMBL ID,Properties,Action Type,Standard Text Value,Value
0,CHEMBL439555,NaN,NaN,2576.15,NaN,NaN,53,Cc1cc(C)cc(CC(=O)N[C@@H](CC(N)=O)C(=O)NC[C@@H]...,MIC,'=',...,CHEMBL1145390,1,Scientific Literature,J Med Chem,2007,NaN,NaN,NaN,NaN,0.25
1,CHEMBL427420,NaN,NaN,2548.10,NaN,NaN,47,Cc1ccccc1C(=O)N[C@@H](CC(N)=O)C(=O)NC[C@@H]1C(...,MIC,'=',...,CHEMBL1145390,1,Scientific Literature,J Med Chem,2007,NaN,NaN,NaN,NaN,2.00
2,CHEMBL266737,NaN,NaN,2552.13,NaN,NaN,45,CC/C=C/C=C\CC(=O)N[C@@H](CC(N)=O)C(=O)NC[C@@H]...,MIC,'=',...,CHEMBL1145390,1,Scientific Literature,J Med Chem,2007,NaN,NaN,NaN,NaN,0.50
3,CHEMBL441753,NaN,NaN,2576.15,NaN,NaN,55,Cc1ccccc1C(C)C(=O)N[C@@H](CC(N)=O)C(=O)NC[C@@H...,MIC,'=',...,CHEMBL1145390,1,Scientific Literature,J Med Chem,2007,NaN,NaN,NaN,NaN,1.00
4,CHEMBL226565,NaN,NaN,2562.12,NaN,NaN,48,Cc1ccccc1CC(=O)N[C@@H](CC(N)=O)C(=O)NC[C@@H]1C...,MIC,'=',...,CHEMBL1145390,1,Scientific Literature,J Med Chem,2007,NaN,NaN,NaN,NaN,0.50


In [17]:
# ============================================================
# CELL 5: MOLECULAR ENCODING
# Morgan Fingerprints (radius=2, 2048 bits)
#   → StandardScaler
#   → PCA to 4 features (one per qubit)
#   → Scale to [-π, π] for AngleEmbedding
# ============================================================

N_QUBITS = 4      # 4 qubits = 4 input features per molecule
N_PCA_COMPONENTS = N_QUBITS

def smiles_to_morgan_fp(smiles, radius=2, nbits=2048):
    """
    Convert SMILES string → Morgan circular fingerprint (bit vector).
    Morgan FP captures local molecular environment around each atom.
    radius=2 is equivalent to ECFP4 used in drug discovery literature.
    """
    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        return classical_np.zeros(nbits)
    fp = GetMorganFingerprintAsBitVect(mol, radius=radius, nBits=nbits)
    return classical_np.array(fp)

print("🔬 Generating Morgan Fingerprints (ECFP4, 2048 bits)...")
fp_matrix = classical_np.array([
    smiles_to_morgan_fp(smi) for smi in df['Smiles']
])
labels = df['label'].values

print(f"✅ Fingerprint matrix shape: {fp_matrix.shape}")

# --- Train/Test Split BEFORE encoding (prevent data leakage) ---
X_train_fp, X_test_fp, y_train, y_test = train_test_split(
    fp_matrix, labels,
    test_size=0.20,
    random_state=SEED,
    stratify=labels
)
print(f"\nTrain size: {len(X_train_fp)} | Test size: {len(X_test_fp)}")

# --- StandardScaler (fit on train only) ---
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train_fp)
X_test_scaled  = scaler.transform(X_test_fp)

# --- PCA: 2048 → 4 features (fit on train only) ---
pca = PCA(n_components=N_PCA_COMPONENTS, random_state=SEED)
X_train_pca = pca.fit_transform(X_train_scaled)
X_test_pca  = pca.transform(X_test_scaled)

print(f"\n📉 PCA variance explained: {pca.explained_variance_ratio_.sum():.3f} ({N_PCA_COMPONENTS} components)")
print(f"Per-component variance: {pca.explained_variance_ratio_}")

# --- Scale features to [-π, π] for AngleEmbedding ---
def scale_to_angle(X):
    """Normalize each feature to range [-pi, pi] for qubit rotation angles."""
    X_min = X.min(axis=0)
    X_max = X.max(axis=0)
    X_norm = (X - X_min) / (X_max - X_min + 1e-8)  # [0, 1]
    return X_norm * 2 * classical_np.pi - classical_np.pi  # [-pi, pi]

X_train_q = scale_to_angle(X_train_pca)
X_test_q  = scale_to_angle(X_test_pca)

# Convert to PennyLane-compatible numpy
X_train_q = classical_np.array(X_train_q)
X_test_q  = classical_np.array(X_test_q)
y_train   = classical_np.array(y_train)
y_test    = classical_np.array(y_test)

print(f"\n✅ Quantum feature matrix (train): {X_train_q.shape}")
print(f"Feature range: [{X_train_q.min():.3f}, {X_train_q.max():.3f}] (should be in [-π, π])")

🔬 Generating Morgan Fingerprints (ECFP4, 2048 bits)...


Streaming output truncated to the last 5000 lines.
[20:46:48] DEPRECATION WARNING: please use MorganGenerator
[20:46:48] DEPRECATION WARNING: please use MorganGenerator
[20:46:48] DEPRECATION WARNING: please use MorganGenerator
[20:46:48] DEPRECATION WARNING: please use MorganGenerator
[20:46:48] DEPRECATION WARNING: please use MorganGenerator
[20:46:48] DEPRECATION WARNING: please use MorganGenerator
[20:46:48] DEPRECATION WARNING: please use MorganGenerator
[20:46:48] DEPRECATION WARNING: please use MorganGenerator
[20:46:48] DEPRECATION WARNING: please use MorganGenerator
[20:46:48] DEPRECATION WARNING: please use MorganGenerator
[20:46:48] DEPRECATION WARNING: please use MorganGenerator
[20:46:48] DEPRECATION WARNING: please use MorganGenerator
[20:46:48] DEPRECATION WARNING: please use MorganGenerator
[20:46:48] DEPRECATION WARNING: please use MorganGenerator
[20:46:48] DEPRECATION WARNING: please use MorganGenerator
[20:46:48] DEPRECATION WARNING: please use MorganGenerator
[20:4

✅ Fingerprint matrix shape: (7471, 2048)

Train size: 5976 | Test size: 1495

📉 PCA variance explained: 0.076 (4 components)
Per-component variance: [0.02827616 0.0187289  0.01579673 0.01328753]

✅ Quantum feature matrix (train): (5976, 4)
Feature range: [-3.142, 3.142] (should be in [-π, π])


In [18]:
# ============================================================
# CELL 6: QUANTUM DEVICE SETUP
# Using Google Cirq simulator via PennyLane-Cirq plugin
# cirq.simulator = Cirq's built-in statevector simulator
# ============================================================

# Number of qubits = number of features after PCA
N_QUBITS = 4
N_LAYERS = 3   # VQC depth: 3 strongly entangling layers

# ---- Define Cirq device ----
# cirq.simulator uses Cirq's native statevector simulation
# Fully compatible with PennyLane's gradient pipeline (parameter-shift rule)
try:
    dev = qml.device('cirq.simulator', wires=N_QUBITS)
    print(f"✅ Quantum device: cirq.simulator")
    print(f"   Wires (qubits): {N_QUBITS}")
    print(f"   VQC Layers: {N_LAYERS}")
except Exception as e:
    print(f"⚠️  Cirq backend not available, falling back to default.qubit")
    print(f"   Error: {e}")
    dev = qml.device('default.qubit', wires=N_QUBITS)
    print("✅ Using PennyLane default.qubit simulator")

# --- Circuit architecture parameter count ---
# StronglyEntanglingLayers: 3 params per qubit per layer
n_params = N_LAYERS * N_QUBITS * 3
print(f"\n📐 Trainable parameters: {n_params}")
print(f"   Formula: {N_LAYERS} layers × {N_QUBITS} qubits × 3 rotation angles")

✅ Quantum device: cirq.simulator
   Wires (qubits): 4
   VQC Layers: 3

📐 Trainable parameters: 36
   Formula: 3 layers × 4 qubits × 3 rotation angles


In [26]:
# ============================================================
# CELL 7: VARIATIONAL QUANTUM CIRCUIT (VQC) DEFINITION
#
# Architecture:
#   1. AngleEmbedding  → encode 4 molecular features as Ry rotations
#   2. StronglyEntanglingLayers (3) → parameterized Ry, Rz + CNOT entanglement
#   3. Measurement → expectation value of PauliZ on qubit 0
#   4. Sigmoid → binary classification probability
#
# Loss: Binary Cross-Entropy
# Optimizer: Adam (quantum parameter-shift gradient)
# ============================================================

@qml.qnode(dev, interface='autograd', diff_method='parameter-shift')
def vqc_circuit(inputs, weights):
    """
    VQC circuit for binary molecular activity classification.

    Args:
        inputs  : shape (4,) — scaled molecular features from PCA
        weights : shape (N_LAYERS, N_QUBITS, 3) — trainable rotation angles
    Returns:
        float: expectation value <Z₀> ∈ [-1, +1]
    """
    # ---- ENCODING LAYER ----
    # AngleEmbedding: maps each feature xᵢ → Ry(xᵢ) rotation on qubit i
    # This encodes classical molecular information into quantum state
    qml.AngleEmbedding(inputs, wires=range(N_QUBITS), rotation='Y')

    # ---- VARIATIONAL LAYERS ----
    # StronglyEntanglingLayers: each layer applies:
    #   Ry(θ) + Rz(φ) on each qubit, followed by
    #   CNOT entanglement gates between neighboring qubits
    qml.StronglyEntanglingLayers(weights, wires=range(N_QUBITS))

    # ---- MEASUREMENT ----
    # Measure expectation value of Pauli-Z on qubit 0
    # Result ∈ [-1, +1]; we map this to [0, 1] for binary classification
    return qml.expval(qml.PauliZ(0))


def sigmoid(x):
    """Map VQC output [-1, +1] → probability [0, 1]"""
    # Use PennyLane's numpy for differentiability
    return 1 / (1 + np.exp(-x * 5))  # scale factor 5 for sharper decision


def predict_proba(X, weights):
    """Get probability predictions for a batch of molecules."""
    probs = []
    for x in X:
        raw = vqc_circuit(x, weights)
        # No float() needed here, sigmoid handles ArrayBox
        prob = sigmoid(raw)
        probs.append(prob)
    return classical_np.array(probs)


def predict(X, weights, threshold=0.5):
    """Binary predictions (0 or 1)."""
    probs = predict_proba(X, weights)
    return (probs >= threshold).astype(int)


# ---- Draw circuit (first molecule as example) ----
print("🔬 VQC Circuit Architecture:")
weights_example = classical_np.zeros((N_LAYERS, N_QUBITS, 3))
print(qml.draw(vqc_circuit)(X_train_q[0], weights_example))
print(f"\n✅ VQC defined on cirq.simulator | {n_params} trainable parameters")

🔬 VQC Circuit Architecture:
0: ─╭AngleEmbedding(M0)─╭StronglyEntanglingLayers(M1)─┤  <Z>
1: ─├AngleEmbedding(M0)─├StronglyEntanglingLayers(M1)─┤     
2: ─├AngleEmbedding(M0)─├StronglyEntanglingLayers(M1)─┤     
3: ─╰AngleEmbedding(M0)─╰StronglyEntanglingLayers(M1)─┤     

M0 = 
[-2.22301304 -1.57039207 -0.20526634 -0.71760941]
M1 = 
[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]

✅ VQC defined on cirq.simulator | 36 trainable parameters


In [27]:
# ============================================================
# CELL 8: COST FUNCTION — Binary Cross-Entropy
#
# L = -1/N * Σ [y·log(p) + (1-y)·log(1-p)]
#
# This is the standard BCE loss for binary classification.
# We compute it over mini-batches for efficiency.
# Gradients computed via parameter-shift rule (quantum-native).
# ============================================================

def binary_cross_entropy(weights, X_batch, y_batch):
    """
    Binary Cross-Entropy loss for VQC classification.

    Args:
        weights : VQC trainable parameters (N_LAYERS, N_QUBITS, 3)
        X_batch : batch of molecular feature vectors, shape (batch, 4)
        y_batch : true binary labels, shape (batch,)
    Returns:
        float: average BCE loss over batch
    """
    eps = 1e-8  # prevent log(0)
    total_loss = np.array(0.0) # Initialize as PennyLane numpy array for differentiability

    for x, y in zip(X_batch, y_batch):
        raw = vqc_circuit(x, weights)
        p = sigmoid(raw) # Removed float()
        p = np.clip(p, eps, 1 - eps) # Changed to np.clip
        loss = -(y * np.log(p) + (1 - y) * np.log(1 - p)) # Changed to np.log
        total_loss += loss

    return total_loss / len(X_batch)


def cost_fn(weights, X_batch, y_batch):
    """Wrapper for optimizer (must accept weights as first arg)."""
    return binary_cross_entropy(weights, X_batch, y_batch)


print("✅ Cost function defined: Binary Cross-Entropy")
print("   Gradient method: Parameter-Shift Rule (quantum-native)")
print("   Formula: L = -1/N * Σ [y·log(p) + (1-y)·log(1-p)]")

# Quick sanity check
weights_init = classical_np.random.uniform(
    low=-classical_np.pi,
    high=classical_np.pi,
    size=(N_LAYERS, N_QUBITS, 3)
)
# Convert to PennyLane-compatible numpy array if gradients are needed later
weights_init = np.array(weights_init, requires_grad=True)

test_loss = cost_fn(weights_init, X_train_q[:3], y_train[:3])
print(f"\n🧪 Sanity check loss (random weights, 3 samples): {test_loss:.4f}")
print(f"   (Expected ~0.693 = ln(2) for random binary classifier)")

✅ Cost function defined: Binary Cross-Entropy
   Gradient method: Parameter-Shift Rule (quantum-native)
   Formula: L = -1/N * Σ [y·log(p) + (1-y)·log(1-p)]

🧪 Sanity check loss (random weights, 3 samples): 1.5343
   (Expected ~0.693 = ln(2) for random binary classifier)


In [ ]:
# ============================================================
# CELL 9: TRAINING LOOP
#
# Optimizer: PennyLane Adam (quantum-aware)
# Epochs: 60
# Batch size: 16 (mini-batch SGD)
# Learning rate: 0.01
#
# NOTE: Due to quantum circuit simulation overhead,
# runtime is ~15-40 min on CPU. Reduce EPOCHS or BATCH_SIZE
# for faster testing. GPU does NOT accelerate circuit sim.
# ============================================================

EPOCHS     = 60
BATCH_SIZE = 16
LR         = 0.01
LOG_EVERY  = 5     # print progress every N epochs

# Subsample for faster prototyping (remove for full run)
# Use first 200 training samples for quick iteration
# Comment out these 2 lines for full dataset training
SUBSAMPLE = 200
X_tr = X_train_q[:SUBSAMPLE]
y_tr = y_train[:SUBSAMPLE]
# For full training: X_tr, y_tr = X_train_q, y_train

# ---- Initialize optimizer ----
optimizer = qml.AdamOptimizer(stepsize=LR)

# ---- Initialize weights (Xavier-style for quantum) ----
weights = classical_np.random.uniform(
    low=-classical_np.pi / 4,
    high=classical_np.pi / 4,
    size=(N_LAYERS, N_QUBITS, 3)
)
# Convert to PennyLane-compatible numpy array to enable gradient tracking
weights = np.array(weights, requires_grad=True)

# ---- Training history ----
history = {'loss': [], 'train_f1': [], 'epoch_time': []}

n_batches = len(X_tr) // BATCH_SIZE
print(f"🚀 Training VQC on cirq.simulator")
print(f"   Samples: {len(X_tr)} | Epochs: {EPOCHS} | Batch: {BATCH_SIZE}")
print(f"   Batches/epoch: {n_batches} | LR: {LR}")
print(f"   Trainable params: {weights.size}")
print("-" * 55)

total_start = time.time()

for epoch in range(1, EPOCHS + 1):
    epoch_start = time.time()
    epoch_loss = np.array(0.0) # Initialize as PennyLane numpy array

    # Shuffle data each epoch
    perm = classical_np.random.permutation(len(X_tr))
    X_shuffled = X_tr[perm]
    y_shuffled = y_tr[perm]

    # Mini-batch updates
    for b in range(n_batches):
        start = b * BATCH_SIZE
        end   = start + BATCH_SIZE
        X_b = X_shuffled[start:end]
        y_b = y_shuffled[start:end]

        weights, loss = optimizer.step_and_cost(
            lambda w: cost_fn(w, X_b, y_b),
            weights
        )
        epoch_loss += loss # Removed float()

    avg_loss = epoch_loss / n_batches
    epoch_time = time.time() - epoch_start

    # Training F1 (computed every LOG_EVERY epochs)
    if epoch % LOG_EVERY == 0:
        preds_train = predict(X_tr[:50], weights)  # quick sample
        train_f1 = f1_score(y_tr[:50], preds_train, zero_division=0)
        history['train_f1'].append(train_f1)
        print(f"Epoch {epoch:3d}/{EPOCHS} | Loss: {avg_loss:.4f} | "
              f"Train F1: {train_f1:.3f} | Time: {epoch_time:.1f}s")

    history['loss'].append(avg_loss)
    history['epoch_time'].append(epoch_time)

total_time = time.time() - total_start
print("-" * 55)
print(f"✅ Training complete! Total time: {total_time/60:.1f} min")
print(f"   Final loss: {history['loss'][-1]:.4f}")

# Save weights
classical_np.save('vqc_weights_final.npy', classical_np.array(weights))
print("💾 Saved: vqc_weights_final.npy")

🚀 Training VQC on cirq.simulator
   Samples: 200 | Epochs: 60 | Batch: 16
   Batches/epoch: 12 | LR: 0.01
   Trainable params: 36
-------------------------------------------------------
